### ISSUE TITLE
Alteração da variável

### ISSUE THREAD

**Issue by phporath** [phporath/cliprasterloop#2]
Na linha 17 fiz a seguinte alteração:

alteração da variável "feicao_info" para feicoes. 

Dessa forma a variável passou a ser encontrada. Mas continuo com o mesmo erro.

**Comment by kylefelipe** [comment]
mano... posta o erro aqui na issue... 
A modificação vc posta na mensagem de commit
hehh

**Comment by phporath** [comment]
`Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 20, in <module>
NameError: name 'feicoes' is not defined`
